version: 2
paths:
  - exclude:
      - "signoz/**"
      - "**/coverage/**"
      - "coverage/**"
      - "**/*.out"
      - "docs/**"
      - ".trae/**"
      - "services/ccxt-service/*.test.ts"
      - "services/ccxt-service/test-*.js"
      - "services/telegram-service/*.test.ts"
      - "**/test-setup.ts"
      - "**/*_test.go"
      - "test/**"
      - "**/internal/utils/*_test.go"
      - "**/internal/skill/*_test.go"
secrets:
  ignored-matches:
    - name: test-secret-key
      match: test-secret-key
    - name: test-admin-key
      match: test-admin-key
    - name: test-bot-token
      match: test-bot-token
    - name: test-webhook-secret
      match: test-webhook-secret
    - name: secret-key-placeholder
      match: replace-with-secure-secret
    - name: docker-compose-dev-default
      match: "postgres"
    - name: dev-jwt-secret
      match: dev-jwt-secret
    - name: admin-secret-key-change-me
      match: admin-secret-key-change-me
    - name: admin-dev-key-change-in-production
      match: admin-dev-key-change-in-production
    # Masking test patterns - these are fake/test values
    - name: test-stripe-key
      match: "sk_live_abcdef"
    - name: test-stripe-key-short
      match: "sk_live_abc123"
    - name: test-password-placeholder
      match: "secretpassword"
    - name: test-super-secret
      match: "supersecret123"
    - name: test-secret-value
      match: "my-super-secret-value-12345"
    - name: test-password-long
      match: "thisisaverylongpassword123"
    - name: test-api-key
      match: "sk_live_abcdef123456"
    - name: test-jwt-token
      match: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
    - name: test-api-key-mask
      match: "sk_live_test"
    - name: test-password-placeholder-2
      match: "secret123"
    - name: test-password-short
      match: "pass123"
    - name: test-password-simple
      match: "mypass"
    - name: test-secret-generic
      match: "hidden"
    - name: test-secret-key-2
      match: "test-secret-key-12345"
    - name: test-api-key-pattern
      match: "api_key"
    # Documentation example patterns
    - name: your-jwt-token
      match: "your-jwt-token"
    - name: yourdomain-placeholder
      match: "yourdomain"
  ignored-paths:
    # Test files commonly use fake credentials
    - "**/*_test.go"
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/test-setup.ts"
    # Docker compose uses environment variable defaults
    - "docker-compose*.yaml"
    - "docker-compose*.yml"
    # Internal utils for masking (tests contain fake secrets)
    - "**/internal/utils/*_test.go"
    - "**/internal/skill/*_test.go"
