// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: telegram_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "telegram";

export interface SendMessageRequest {
  chatId: string;
  text: string;
  parseMode: string;
}

export interface SendMessageResponse {
  ok: boolean;
  messageId: string;
  error: string;
  /** Structured error code for programmatic handling */
  errorCode: string;
  /** Seconds to wait before retrying (only set for RATE_LIMITED errors) */
  retryAfter: number;
}

export interface HealthCheckRequest {
}

export interface HealthCheckResponse {
  status: string;
  version: string;
  service: string;
}

export interface StreamEventsRequest {
  chatId: string;
}

export interface ActionAlertPayload {
  action: string;
  asset: string;
  price: string;
  size: string;
  strategy: string;
  reasoning: string;
  riskCheckPassed: boolean;
  questId: string;
}

export interface QuestProgressPayload {
  questId: string;
  questName: string;
  current: number;
  target: number;
  percent: number;
  timeRemaining: string;
}

export interface MilestonePayload {
  amount: string;
  phase: string;
  nextTarget: string;
}

export interface RiskEventPayload {
  eventType: string;
  severity: string;
  message: string;
  details: { [key: string]: string };
}

export interface RiskEventPayload_DetailsEntry {
  key: string;
  value: string;
}

export interface TelegramEvent {
  type: string;
  chatId: string;
  timestamp: number;
  action?: ActionAlertPayload | undefined;
  quest?: QuestProgressPayload | undefined;
  milestone?: MilestonePayload | undefined;
  risk?: RiskEventPayload | undefined;
}

export interface SendActionAlertRequest {
  chatId: string;
  action: string;
  asset: string;
  price: string;
  size: string;
  strategy: string;
  reasoning: string;
  riskCheckPassed: boolean;
  questId: string;
}

export interface SendActionAlertResponse {
  ok: boolean;
  messageId: string;
  error: string;
}

export interface SendQuestProgressRequest {
  chatId: string;
  questId: string;
  questName: string;
  current: number;
  target: number;
  percent: number;
  timeRemaining: string;
}

export interface SendQuestProgressResponse {
  ok: boolean;
  messageId: string;
  error: string;
}

export interface SendMilestoneAlertRequest {
  chatId: string;
  amount: string;
  phase: string;
  nextTarget: string;
}

export interface SendMilestoneAlertResponse {
  ok: boolean;
  messageId: string;
  error: string;
}

export interface SendRiskEventRequest {
  chatId: string;
  eventType: string;
  severity: string;
  message: string;
  details: { [key: string]: string };
}

export interface SendRiskEventRequest_DetailsEntry {
  key: string;
  value: string;
}

export interface SendRiskEventResponse {
  ok: boolean;
  messageId: string;
  error: string;
}

function createBaseSendMessageRequest(): SendMessageRequest {
  return { chatId: "", text: "", parseMode: "" };
}

export const SendMessageRequest: MessageFns<SendMessageRequest> = {
  encode(message: SendMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.parseMode !== "") {
      writer.uint32(26).string(message.parseMode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parseMode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessageRequest {
    return {
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      parseMode: isSet(object.parseMode)
        ? globalThis.String(object.parseMode)
        : isSet(object.parse_mode)
        ? globalThis.String(object.parse_mode)
        : "",
    };
  },

  toJSON(message: SendMessageRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.parseMode !== "") {
      obj.parseMode = message.parseMode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessageRequest>, I>>(base?: I): SendMessageRequest {
    return SendMessageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessageRequest>, I>>(object: I): SendMessageRequest {
    const message = createBaseSendMessageRequest();
    message.chatId = object.chatId ?? "";
    message.text = object.text ?? "";
    message.parseMode = object.parseMode ?? "";
    return message;
  },
};

function createBaseSendMessageResponse(): SendMessageResponse {
  return { ok: false, messageId: "", error: "", errorCode: "", retryAfter: 0 };
}

export const SendMessageResponse: MessageFns<SendMessageResponse> = {
  encode(message: SendMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    if (message.errorCode !== "") {
      writer.uint32(34).string(message.errorCode);
    }
    if (message.retryAfter !== 0) {
      writer.uint32(40).int32(message.retryAfter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorCode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.retryAfter = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessageResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      errorCode: isSet(object.errorCode)
        ? globalThis.String(object.errorCode)
        : "",
      retryAfter: isSet(object.retryAfter)
        ? globalThis.Number(object.retryAfter)
        : 0,
    };
  },

  toJSON(message: SendMessageResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.errorCode !== "") {
      obj.errorCode = message.errorCode;
    }
    if (message.retryAfter !== 0) {
      obj.retryAfter = message.retryAfter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessageResponse>, I>>(base?: I): SendMessageResponse {
    return SendMessageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessageResponse>, I>>(object: I): SendMessageResponse {
    const message = createBaseSendMessageResponse();
    message.ok = object.ok ?? false;
    message.messageId = object.messageId ?? "";
    message.error = object.error ?? "";
    message.errorCode = object.errorCode ?? "";
    message.retryAfter = object.retryAfter ?? 0;
    return message;
  },
};

function createBaseHealthCheckRequest(): HealthCheckRequest {
  return {};
}

export const HealthCheckRequest: MessageFns<HealthCheckRequest> = {
  encode(_: HealthCheckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthCheckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHealthCheckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HealthCheckRequest {
    return {};
  },

  toJSON(_: HealthCheckRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HealthCheckRequest>, I>>(base?: I): HealthCheckRequest {
    return HealthCheckRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HealthCheckRequest>, I>>(_: I): HealthCheckRequest {
    const message = createBaseHealthCheckRequest();
    return message;
  },
};

function createBaseHealthCheckResponse(): HealthCheckResponse {
  return { status: "", version: "", service: "" };
}

export const HealthCheckResponse: MessageFns<HealthCheckResponse> = {
  encode(message: HealthCheckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.service !== "") {
      writer.uint32(26).string(message.service);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthCheckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHealthCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.service = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HealthCheckResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      service: isSet(object.service) ? globalThis.String(object.service) : "",
    };
  },

  toJSON(message: HealthCheckResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.service !== "") {
      obj.service = message.service;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HealthCheckResponse>, I>>(base?: I): HealthCheckResponse {
    return HealthCheckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HealthCheckResponse>, I>>(object: I): HealthCheckResponse {
    const message = createBaseHealthCheckResponse();
    message.status = object.status ?? "";
    message.version = object.version ?? "";
    message.service = object.service ?? "";
    return message;
  },
};

function createBaseStreamEventsRequest(): StreamEventsRequest {
  return { chatId: "" };
}

export const StreamEventsRequest: MessageFns<StreamEventsRequest> = {
  encode(message: StreamEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamEventsRequest {
    return {
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
    };
  },

  toJSON(message: StreamEventsRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamEventsRequest>, I>>(base?: I): StreamEventsRequest {
    return StreamEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamEventsRequest>, I>>(object: I): StreamEventsRequest {
    const message = createBaseStreamEventsRequest();
    message.chatId = object.chatId ?? "";
    return message;
  },
};

function createBaseActionAlertPayload(): ActionAlertPayload {
  return {
    action: "",
    asset: "",
    price: "",
    size: "",
    strategy: "",
    reasoning: "",
    riskCheckPassed: false,
    questId: "",
  };
}

export const ActionAlertPayload: MessageFns<ActionAlertPayload> = {
  encode(message: ActionAlertPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== "") {
      writer.uint32(10).string(message.action);
    }
    if (message.asset !== "") {
      writer.uint32(18).string(message.asset);
    }
    if (message.price !== "") {
      writer.uint32(26).string(message.price);
    }
    if (message.size !== "") {
      writer.uint32(34).string(message.size);
    }
    if (message.strategy !== "") {
      writer.uint32(42).string(message.strategy);
    }
    if (message.reasoning !== "") {
      writer.uint32(50).string(message.reasoning);
    }
    if (message.riskCheckPassed !== false) {
      writer.uint32(56).bool(message.riskCheckPassed);
    }
    if (message.questId !== "") {
      writer.uint32(66).string(message.questId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionAlertPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionAlertPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.size = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.strategy = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.reasoning = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.riskCheckPassed = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.questId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionAlertPayload {
    return {
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      size: isSet(object.size) ? globalThis.String(object.size) : "",
      strategy: isSet(object.strategy) ? globalThis.String(object.strategy) : "",
      reasoning: isSet(object.reasoning) ? globalThis.String(object.reasoning) : "",
      riskCheckPassed: isSet(object.riskCheckPassed)
        ? globalThis.Boolean(object.riskCheckPassed)
        : isSet(object.risk_check_passed)
        ? globalThis.Boolean(object.risk_check_passed)
        : false,
      questId: isSet(object.questId)
        ? globalThis.String(object.questId)
        : isSet(object.quest_id)
        ? globalThis.String(object.quest_id)
        : "",
    };
  },

  toJSON(message: ActionAlertPayload): unknown {
    const obj: any = {};
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.price !== "") {
      obj.price = message.price;
    }
    if (message.size !== "") {
      obj.size = message.size;
    }
    if (message.strategy !== "") {
      obj.strategy = message.strategy;
    }
    if (message.reasoning !== "") {
      obj.reasoning = message.reasoning;
    }
    if (message.riskCheckPassed !== false) {
      obj.riskCheckPassed = message.riskCheckPassed;
    }
    if (message.questId !== "") {
      obj.questId = message.questId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionAlertPayload>, I>>(base?: I): ActionAlertPayload {
    return ActionAlertPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionAlertPayload>, I>>(object: I): ActionAlertPayload {
    const message = createBaseActionAlertPayload();
    message.action = object.action ?? "";
    message.asset = object.asset ?? "";
    message.price = object.price ?? "";
    message.size = object.size ?? "";
    message.strategy = object.strategy ?? "";
    message.reasoning = object.reasoning ?? "";
    message.riskCheckPassed = object.riskCheckPassed ?? false;
    message.questId = object.questId ?? "";
    return message;
  },
};

function createBaseQuestProgressPayload(): QuestProgressPayload {
  return { questId: "", questName: "", current: 0, target: 0, percent: 0, timeRemaining: "" };
}

export const QuestProgressPayload: MessageFns<QuestProgressPayload> = {
  encode(message: QuestProgressPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.questId !== "") {
      writer.uint32(10).string(message.questId);
    }
    if (message.questName !== "") {
      writer.uint32(18).string(message.questName);
    }
    if (message.current !== 0) {
      writer.uint32(24).int32(message.current);
    }
    if (message.target !== 0) {
      writer.uint32(32).int32(message.target);
    }
    if (message.percent !== 0) {
      writer.uint32(40).int32(message.percent);
    }
    if (message.timeRemaining !== "") {
      writer.uint32(50).string(message.timeRemaining);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuestProgressPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuestProgressPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.questId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.questName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.current = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.target = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.percent = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timeRemaining = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuestProgressPayload {
    return {
      questId: isSet(object.questId)
        ? globalThis.String(object.questId)
        : isSet(object.quest_id)
        ? globalThis.String(object.quest_id)
        : "",
      questName: isSet(object.questName)
        ? globalThis.String(object.questName)
        : isSet(object.quest_name)
        ? globalThis.String(object.quest_name)
        : "",
      current: isSet(object.current) ? globalThis.Number(object.current) : 0,
      target: isSet(object.target) ? globalThis.Number(object.target) : 0,
      percent: isSet(object.percent) ? globalThis.Number(object.percent) : 0,
      timeRemaining: isSet(object.timeRemaining)
        ? globalThis.String(object.timeRemaining)
        : isSet(object.time_remaining)
        ? globalThis.String(object.time_remaining)
        : "",
    };
  },

  toJSON(message: QuestProgressPayload): unknown {
    const obj: any = {};
    if (message.questId !== "") {
      obj.questId = message.questId;
    }
    if (message.questName !== "") {
      obj.questName = message.questName;
    }
    if (message.current !== 0) {
      obj.current = Math.round(message.current);
    }
    if (message.target !== 0) {
      obj.target = Math.round(message.target);
    }
    if (message.percent !== 0) {
      obj.percent = Math.round(message.percent);
    }
    if (message.timeRemaining !== "") {
      obj.timeRemaining = message.timeRemaining;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuestProgressPayload>, I>>(base?: I): QuestProgressPayload {
    return QuestProgressPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuestProgressPayload>, I>>(object: I): QuestProgressPayload {
    const message = createBaseQuestProgressPayload();
    message.questId = object.questId ?? "";
    message.questName = object.questName ?? "";
    message.current = object.current ?? 0;
    message.target = object.target ?? 0;
    message.percent = object.percent ?? 0;
    message.timeRemaining = object.timeRemaining ?? "";
    return message;
  },
};

function createBaseMilestonePayload(): MilestonePayload {
  return { amount: "", phase: "", nextTarget: "" };
}

export const MilestonePayload: MessageFns<MilestonePayload> = {
  encode(message: MilestonePayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    if (message.phase !== "") {
      writer.uint32(18).string(message.phase);
    }
    if (message.nextTarget !== "") {
      writer.uint32(26).string(message.nextTarget);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MilestonePayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMilestonePayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nextTarget = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MilestonePayload {
    return {
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      nextTarget: isSet(object.nextTarget)
        ? globalThis.String(object.nextTarget)
        : isSet(object.next_target)
        ? globalThis.String(object.next_target)
        : "",
    };
  },

  toJSON(message: MilestonePayload): unknown {
    const obj: any = {};
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.nextTarget !== "") {
      obj.nextTarget = message.nextTarget;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MilestonePayload>, I>>(base?: I): MilestonePayload {
    return MilestonePayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MilestonePayload>, I>>(object: I): MilestonePayload {
    const message = createBaseMilestonePayload();
    message.amount = object.amount ?? "";
    message.phase = object.phase ?? "";
    message.nextTarget = object.nextTarget ?? "";
    return message;
  },
};

function createBaseRiskEventPayload(): RiskEventPayload {
  return { eventType: "", severity: "", message: "", details: {} };
}

export const RiskEventPayload: MessageFns<RiskEventPayload> = {
  encode(message: RiskEventPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== "") {
      writer.uint32(10).string(message.eventType);
    }
    if (message.severity !== "") {
      writer.uint32(18).string(message.severity);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    globalThis.Object.entries(message.details).forEach(([key, value]: [string, string]) => {
      RiskEventPayload_DetailsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RiskEventPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRiskEventPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.severity = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = RiskEventPayload_DetailsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.details[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RiskEventPayload {
    return {
      eventType: isSet(object.eventType)
        ? globalThis.String(object.eventType)
        : isSet(object.event_type)
        ? globalThis.String(object.event_type)
        : "",
      severity: isSet(object.severity) ? globalThis.String(object.severity) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      details: isObject(object.details)
        ? (globalThis.Object.entries(object.details) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: RiskEventPayload): unknown {
    const obj: any = {};
    if (message.eventType !== "") {
      obj.eventType = message.eventType;
    }
    if (message.severity !== "") {
      obj.severity = message.severity;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.details) {
      const entries = globalThis.Object.entries(message.details) as [string, string][];
      if (entries.length > 0) {
        obj.details = {};
        entries.forEach(([k, v]) => {
          obj.details[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RiskEventPayload>, I>>(base?: I): RiskEventPayload {
    return RiskEventPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RiskEventPayload>, I>>(object: I): RiskEventPayload {
    const message = createBaseRiskEventPayload();
    message.eventType = object.eventType ?? "";
    message.severity = object.severity ?? "";
    message.message = object.message ?? "";
    message.details = (globalThis.Object.entries(object.details ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseRiskEventPayload_DetailsEntry(): RiskEventPayload_DetailsEntry {
  return { key: "", value: "" };
}

export const RiskEventPayload_DetailsEntry: MessageFns<RiskEventPayload_DetailsEntry> = {
  encode(message: RiskEventPayload_DetailsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RiskEventPayload_DetailsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRiskEventPayload_DetailsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RiskEventPayload_DetailsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: RiskEventPayload_DetailsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RiskEventPayload_DetailsEntry>, I>>(base?: I): RiskEventPayload_DetailsEntry {
    return RiskEventPayload_DetailsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RiskEventPayload_DetailsEntry>, I>>(
    object: I,
  ): RiskEventPayload_DetailsEntry {
    const message = createBaseRiskEventPayload_DetailsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseTelegramEvent(): TelegramEvent {
  return {
    type: "",
    chatId: "",
    timestamp: 0,
    action: undefined,
    quest: undefined,
    milestone: undefined,
    risk: undefined,
  };
}

export const TelegramEvent: MessageFns<TelegramEvent> = {
  encode(message: TelegramEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.chatId !== "") {
      writer.uint32(18).string(message.chatId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    if (message.action !== undefined) {
      ActionAlertPayload.encode(message.action, writer.uint32(34).fork()).join();
    }
    if (message.quest !== undefined) {
      QuestProgressPayload.encode(message.quest, writer.uint32(42).fork()).join();
    }
    if (message.milestone !== undefined) {
      MilestonePayload.encode(message.milestone, writer.uint32(50).fork()).join();
    }
    if (message.risk !== undefined) {
      RiskEventPayload.encode(message.risk, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TelegramEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTelegramEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.action = ActionAlertPayload.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.quest = QuestProgressPayload.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.milestone = MilestonePayload.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.risk = RiskEventPayload.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TelegramEvent {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      action: isSet(object.action) ? ActionAlertPayload.fromJSON(object.action) : undefined,
      quest: isSet(object.quest) ? QuestProgressPayload.fromJSON(object.quest) : undefined,
      milestone: isSet(object.milestone) ? MilestonePayload.fromJSON(object.milestone) : undefined,
      risk: isSet(object.risk) ? RiskEventPayload.fromJSON(object.risk) : undefined,
    };
  },

  toJSON(message: TelegramEvent): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.action !== undefined) {
      obj.action = ActionAlertPayload.toJSON(message.action);
    }
    if (message.quest !== undefined) {
      obj.quest = QuestProgressPayload.toJSON(message.quest);
    }
    if (message.milestone !== undefined) {
      obj.milestone = MilestonePayload.toJSON(message.milestone);
    }
    if (message.risk !== undefined) {
      obj.risk = RiskEventPayload.toJSON(message.risk);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TelegramEvent>, I>>(base?: I): TelegramEvent {
    return TelegramEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TelegramEvent>, I>>(object: I): TelegramEvent {
    const message = createBaseTelegramEvent();
    message.type = object.type ?? "";
    message.chatId = object.chatId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.action = (object.action !== undefined && object.action !== null)
      ? ActionAlertPayload.fromPartial(object.action)
      : undefined;
    message.quest = (object.quest !== undefined && object.quest !== null)
      ? QuestProgressPayload.fromPartial(object.quest)
      : undefined;
    message.milestone = (object.milestone !== undefined && object.milestone !== null)
      ? MilestonePayload.fromPartial(object.milestone)
      : undefined;
    message.risk = (object.risk !== undefined && object.risk !== null)
      ? RiskEventPayload.fromPartial(object.risk)
      : undefined;
    return message;
  },
};

function createBaseSendActionAlertRequest(): SendActionAlertRequest {
  return {
    chatId: "",
    action: "",
    asset: "",
    price: "",
    size: "",
    strategy: "",
    reasoning: "",
    riskCheckPassed: false,
    questId: "",
  };
}

export const SendActionAlertRequest: MessageFns<SendActionAlertRequest> = {
  encode(message: SendActionAlertRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    if (message.action !== "") {
      writer.uint32(18).string(message.action);
    }
    if (message.asset !== "") {
      writer.uint32(26).string(message.asset);
    }
    if (message.price !== "") {
      writer.uint32(34).string(message.price);
    }
    if (message.size !== "") {
      writer.uint32(42).string(message.size);
    }
    if (message.strategy !== "") {
      writer.uint32(50).string(message.strategy);
    }
    if (message.reasoning !== "") {
      writer.uint32(58).string(message.reasoning);
    }
    if (message.riskCheckPassed !== false) {
      writer.uint32(64).bool(message.riskCheckPassed);
    }
    if (message.questId !== "") {
      writer.uint32(74).string(message.questId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendActionAlertRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendActionAlertRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.size = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.strategy = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.reasoning = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.riskCheckPassed = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.questId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendActionAlertRequest {
    return {
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      size: isSet(object.size) ? globalThis.String(object.size) : "",
      strategy: isSet(object.strategy) ? globalThis.String(object.strategy) : "",
      reasoning: isSet(object.reasoning) ? globalThis.String(object.reasoning) : "",
      riskCheckPassed: isSet(object.riskCheckPassed)
        ? globalThis.Boolean(object.riskCheckPassed)
        : isSet(object.risk_check_passed)
        ? globalThis.Boolean(object.risk_check_passed)
        : false,
      questId: isSet(object.questId)
        ? globalThis.String(object.questId)
        : isSet(object.quest_id)
        ? globalThis.String(object.quest_id)
        : "",
    };
  },

  toJSON(message: SendActionAlertRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.price !== "") {
      obj.price = message.price;
    }
    if (message.size !== "") {
      obj.size = message.size;
    }
    if (message.strategy !== "") {
      obj.strategy = message.strategy;
    }
    if (message.reasoning !== "") {
      obj.reasoning = message.reasoning;
    }
    if (message.riskCheckPassed !== false) {
      obj.riskCheckPassed = message.riskCheckPassed;
    }
    if (message.questId !== "") {
      obj.questId = message.questId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendActionAlertRequest>, I>>(base?: I): SendActionAlertRequest {
    return SendActionAlertRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendActionAlertRequest>, I>>(object: I): SendActionAlertRequest {
    const message = createBaseSendActionAlertRequest();
    message.chatId = object.chatId ?? "";
    message.action = object.action ?? "";
    message.asset = object.asset ?? "";
    message.price = object.price ?? "";
    message.size = object.size ?? "";
    message.strategy = object.strategy ?? "";
    message.reasoning = object.reasoning ?? "";
    message.riskCheckPassed = object.riskCheckPassed ?? false;
    message.questId = object.questId ?? "";
    return message;
  },
};

function createBaseSendActionAlertResponse(): SendActionAlertResponse {
  return { ok: false, messageId: "", error: "" };
}

export const SendActionAlertResponse: MessageFns<SendActionAlertResponse> = {
  encode(message: SendActionAlertResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendActionAlertResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendActionAlertResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendActionAlertResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: SendActionAlertResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendActionAlertResponse>, I>>(base?: I): SendActionAlertResponse {
    return SendActionAlertResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendActionAlertResponse>, I>>(object: I): SendActionAlertResponse {
    const message = createBaseSendActionAlertResponse();
    message.ok = object.ok ?? false;
    message.messageId = object.messageId ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseSendQuestProgressRequest(): SendQuestProgressRequest {
  return { chatId: "", questId: "", questName: "", current: 0, target: 0, percent: 0, timeRemaining: "" };
}

export const SendQuestProgressRequest: MessageFns<SendQuestProgressRequest> = {
  encode(message: SendQuestProgressRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    if (message.questId !== "") {
      writer.uint32(18).string(message.questId);
    }
    if (message.questName !== "") {
      writer.uint32(26).string(message.questName);
    }
    if (message.current !== 0) {
      writer.uint32(32).int32(message.current);
    }
    if (message.target !== 0) {
      writer.uint32(40).int32(message.target);
    }
    if (message.percent !== 0) {
      writer.uint32(48).int32(message.percent);
    }
    if (message.timeRemaining !== "") {
      writer.uint32(58).string(message.timeRemaining);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendQuestProgressRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendQuestProgressRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.questId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.questName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.current = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.target = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.percent = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.timeRemaining = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendQuestProgressRequest {
    return {
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
      questId: isSet(object.questId)
        ? globalThis.String(object.questId)
        : isSet(object.quest_id)
        ? globalThis.String(object.quest_id)
        : "",
      questName: isSet(object.questName)
        ? globalThis.String(object.questName)
        : isSet(object.quest_name)
        ? globalThis.String(object.quest_name)
        : "",
      current: isSet(object.current) ? globalThis.Number(object.current) : 0,
      target: isSet(object.target) ? globalThis.Number(object.target) : 0,
      percent: isSet(object.percent) ? globalThis.Number(object.percent) : 0,
      timeRemaining: isSet(object.timeRemaining)
        ? globalThis.String(object.timeRemaining)
        : isSet(object.time_remaining)
        ? globalThis.String(object.time_remaining)
        : "",
    };
  },

  toJSON(message: SendQuestProgressRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.questId !== "") {
      obj.questId = message.questId;
    }
    if (message.questName !== "") {
      obj.questName = message.questName;
    }
    if (message.current !== 0) {
      obj.current = Math.round(message.current);
    }
    if (message.target !== 0) {
      obj.target = Math.round(message.target);
    }
    if (message.percent !== 0) {
      obj.percent = Math.round(message.percent);
    }
    if (message.timeRemaining !== "") {
      obj.timeRemaining = message.timeRemaining;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendQuestProgressRequest>, I>>(base?: I): SendQuestProgressRequest {
    return SendQuestProgressRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendQuestProgressRequest>, I>>(object: I): SendQuestProgressRequest {
    const message = createBaseSendQuestProgressRequest();
    message.chatId = object.chatId ?? "";
    message.questId = object.questId ?? "";
    message.questName = object.questName ?? "";
    message.current = object.current ?? 0;
    message.target = object.target ?? 0;
    message.percent = object.percent ?? 0;
    message.timeRemaining = object.timeRemaining ?? "";
    return message;
  },
};

function createBaseSendQuestProgressResponse(): SendQuestProgressResponse {
  return { ok: false, messageId: "", error: "" };
}

export const SendQuestProgressResponse: MessageFns<SendQuestProgressResponse> = {
  encode(message: SendQuestProgressResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendQuestProgressResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendQuestProgressResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendQuestProgressResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: SendQuestProgressResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendQuestProgressResponse>, I>>(base?: I): SendQuestProgressResponse {
    return SendQuestProgressResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendQuestProgressResponse>, I>>(object: I): SendQuestProgressResponse {
    const message = createBaseSendQuestProgressResponse();
    message.ok = object.ok ?? false;
    message.messageId = object.messageId ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseSendMilestoneAlertRequest(): SendMilestoneAlertRequest {
  return { chatId: "", amount: "", phase: "", nextTarget: "" };
}

export const SendMilestoneAlertRequest: MessageFns<SendMilestoneAlertRequest> = {
  encode(message: SendMilestoneAlertRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.phase !== "") {
      writer.uint32(26).string(message.phase);
    }
    if (message.nextTarget !== "") {
      writer.uint32(34).string(message.nextTarget);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMilestoneAlertRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMilestoneAlertRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nextTarget = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMilestoneAlertRequest {
    return {
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      nextTarget: isSet(object.nextTarget)
        ? globalThis.String(object.nextTarget)
        : isSet(object.next_target)
        ? globalThis.String(object.next_target)
        : "",
    };
  },

  toJSON(message: SendMilestoneAlertRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.nextTarget !== "") {
      obj.nextTarget = message.nextTarget;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMilestoneAlertRequest>, I>>(base?: I): SendMilestoneAlertRequest {
    return SendMilestoneAlertRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMilestoneAlertRequest>, I>>(object: I): SendMilestoneAlertRequest {
    const message = createBaseSendMilestoneAlertRequest();
    message.chatId = object.chatId ?? "";
    message.amount = object.amount ?? "";
    message.phase = object.phase ?? "";
    message.nextTarget = object.nextTarget ?? "";
    return message;
  },
};

function createBaseSendMilestoneAlertResponse(): SendMilestoneAlertResponse {
  return { ok: false, messageId: "", error: "" };
}

export const SendMilestoneAlertResponse: MessageFns<SendMilestoneAlertResponse> = {
  encode(message: SendMilestoneAlertResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMilestoneAlertResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMilestoneAlertResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMilestoneAlertResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: SendMilestoneAlertResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMilestoneAlertResponse>, I>>(base?: I): SendMilestoneAlertResponse {
    return SendMilestoneAlertResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMilestoneAlertResponse>, I>>(object: I): SendMilestoneAlertResponse {
    const message = createBaseSendMilestoneAlertResponse();
    message.ok = object.ok ?? false;
    message.messageId = object.messageId ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseSendRiskEventRequest(): SendRiskEventRequest {
  return { chatId: "", eventType: "", severity: "", message: "", details: {} };
}

export const SendRiskEventRequest: MessageFns<SendRiskEventRequest> = {
  encode(message: SendRiskEventRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chatId !== "") {
      writer.uint32(10).string(message.chatId);
    }
    if (message.eventType !== "") {
      writer.uint32(18).string(message.eventType);
    }
    if (message.severity !== "") {
      writer.uint32(26).string(message.severity);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    globalThis.Object.entries(message.details).forEach(([key, value]: [string, string]) => {
      SendRiskEventRequest_DetailsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendRiskEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendRiskEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chatId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.severity = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = SendRiskEventRequest_DetailsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.details[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendRiskEventRequest {
    return {
      chatId: isSet(object.chatId)
        ? globalThis.String(object.chatId)
        : isSet(object.chat_id)
        ? globalThis.String(object.chat_id)
        : "",
      eventType: isSet(object.eventType)
        ? globalThis.String(object.eventType)
        : isSet(object.event_type)
        ? globalThis.String(object.event_type)
        : "",
      severity: isSet(object.severity) ? globalThis.String(object.severity) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      details: isObject(object.details)
        ? (globalThis.Object.entries(object.details) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: SendRiskEventRequest): unknown {
    const obj: any = {};
    if (message.chatId !== "") {
      obj.chatId = message.chatId;
    }
    if (message.eventType !== "") {
      obj.eventType = message.eventType;
    }
    if (message.severity !== "") {
      obj.severity = message.severity;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.details) {
      const entries = globalThis.Object.entries(message.details) as [string, string][];
      if (entries.length > 0) {
        obj.details = {};
        entries.forEach(([k, v]) => {
          obj.details[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendRiskEventRequest>, I>>(base?: I): SendRiskEventRequest {
    return SendRiskEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendRiskEventRequest>, I>>(object: I): SendRiskEventRequest {
    const message = createBaseSendRiskEventRequest();
    message.chatId = object.chatId ?? "";
    message.eventType = object.eventType ?? "";
    message.severity = object.severity ?? "";
    message.message = object.message ?? "";
    message.details = (globalThis.Object.entries(object.details ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseSendRiskEventRequest_DetailsEntry(): SendRiskEventRequest_DetailsEntry {
  return { key: "", value: "" };
}

export const SendRiskEventRequest_DetailsEntry: MessageFns<SendRiskEventRequest_DetailsEntry> = {
  encode(message: SendRiskEventRequest_DetailsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendRiskEventRequest_DetailsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendRiskEventRequest_DetailsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendRiskEventRequest_DetailsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SendRiskEventRequest_DetailsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendRiskEventRequest_DetailsEntry>, I>>(
    base?: I,
  ): SendRiskEventRequest_DetailsEntry {
    return SendRiskEventRequest_DetailsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendRiskEventRequest_DetailsEntry>, I>>(
    object: I,
  ): SendRiskEventRequest_DetailsEntry {
    const message = createBaseSendRiskEventRequest_DetailsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSendRiskEventResponse(): SendRiskEventResponse {
  return { ok: false, messageId: "", error: "" };
}

export const SendRiskEventResponse: MessageFns<SendRiskEventResponse> = {
  encode(message: SendRiskEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.messageId !== "") {
      writer.uint32(18).string(message.messageId);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendRiskEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendRiskEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendRiskEventResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: SendRiskEventResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendRiskEventResponse>, I>>(base?: I): SendRiskEventResponse {
    return SendRiskEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendRiskEventResponse>, I>>(object: I): SendRiskEventResponse {
    const message = createBaseSendRiskEventResponse();
    message.ok = object.ok ?? false;
    message.messageId = object.messageId ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

export type TelegramServiceService = typeof TelegramServiceService;
export const TelegramServiceService = {
  sendMessage: {
    path: "/telegram.TelegramService/SendMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendMessageRequest): Buffer => Buffer.from(SendMessageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendMessageRequest => SendMessageRequest.decode(value),
    responseSerialize: (value: SendMessageResponse): Buffer => Buffer.from(SendMessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendMessageResponse => SendMessageResponse.decode(value),
  },
  healthCheck: {
    path: "/telegram.TelegramService/HealthCheck",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  streamEvents: {
    path: "/telegram.TelegramService/StreamEvents",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: StreamEventsRequest): Buffer => Buffer.from(StreamEventsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StreamEventsRequest => StreamEventsRequest.decode(value),
    responseSerialize: (value: TelegramEvent): Buffer => Buffer.from(TelegramEvent.encode(value).finish()),
    responseDeserialize: (value: Buffer): TelegramEvent => TelegramEvent.decode(value),
  },
  sendActionAlert: {
    path: "/telegram.TelegramService/SendActionAlert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendActionAlertRequest): Buffer =>
      Buffer.from(SendActionAlertRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendActionAlertRequest => SendActionAlertRequest.decode(value),
    responseSerialize: (value: SendActionAlertResponse): Buffer =>
      Buffer.from(SendActionAlertResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendActionAlertResponse => SendActionAlertResponse.decode(value),
  },
  sendQuestProgress: {
    path: "/telegram.TelegramService/SendQuestProgress",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendQuestProgressRequest): Buffer =>
      Buffer.from(SendQuestProgressRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendQuestProgressRequest => SendQuestProgressRequest.decode(value),
    responseSerialize: (value: SendQuestProgressResponse): Buffer =>
      Buffer.from(SendQuestProgressResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendQuestProgressResponse => SendQuestProgressResponse.decode(value),
  },
  sendMilestoneAlert: {
    path: "/telegram.TelegramService/SendMilestoneAlert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendMilestoneAlertRequest): Buffer =>
      Buffer.from(SendMilestoneAlertRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendMilestoneAlertRequest => SendMilestoneAlertRequest.decode(value),
    responseSerialize: (value: SendMilestoneAlertResponse): Buffer =>
      Buffer.from(SendMilestoneAlertResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendMilestoneAlertResponse => SendMilestoneAlertResponse.decode(value),
  },
  sendRiskEvent: {
    path: "/telegram.TelegramService/SendRiskEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendRiskEventRequest): Buffer => Buffer.from(SendRiskEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendRiskEventRequest => SendRiskEventRequest.decode(value),
    responseSerialize: (value: SendRiskEventResponse): Buffer =>
      Buffer.from(SendRiskEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendRiskEventResponse => SendRiskEventResponse.decode(value),
  },
} as const;

export interface TelegramServiceServer extends UntypedServiceImplementation {
  sendMessage: handleUnaryCall<SendMessageRequest, SendMessageResponse>;
  healthCheck: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  streamEvents: handleServerStreamingCall<StreamEventsRequest, TelegramEvent>;
  sendActionAlert: handleUnaryCall<SendActionAlertRequest, SendActionAlertResponse>;
  sendQuestProgress: handleUnaryCall<SendQuestProgressRequest, SendQuestProgressResponse>;
  sendMilestoneAlert: handleUnaryCall<SendMilestoneAlertRequest, SendMilestoneAlertResponse>;
  sendRiskEvent: handleUnaryCall<SendRiskEventRequest, SendRiskEventResponse>;
}

export interface TelegramServiceClient extends Client {
  sendMessage(
    request: SendMessageRequest,
    callback: (error: ServiceError | null, response: SendMessageResponse) => void,
  ): ClientUnaryCall;
  sendMessage(
    request: SendMessageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SendMessageResponse) => void,
  ): ClientUnaryCall;
  sendMessage(
    request: SendMessageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SendMessageResponse) => void,
  ): ClientUnaryCall;
  healthCheck(
    request: HealthCheckRequest,
    callback: (error: ServiceError | null, response: HealthCheckResponse) => void,
  ): ClientUnaryCall;
  healthCheck(
    request: HealthCheckRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HealthCheckResponse) => void,
  ): ClientUnaryCall;
  healthCheck(
    request: HealthCheckRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HealthCheckResponse) => void,
  ): ClientUnaryCall;
  streamEvents(request: StreamEventsRequest, options?: Partial<CallOptions>): ClientReadableStream<TelegramEvent>;
  streamEvents(
    request: StreamEventsRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<TelegramEvent>;
  sendActionAlert(
    request: SendActionAlertRequest,
    callback: (error: ServiceError | null, response: SendActionAlertResponse) => void,
  ): ClientUnaryCall;
  sendActionAlert(
    request: SendActionAlertRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SendActionAlertResponse) => void,
  ): ClientUnaryCall;
  sendActionAlert(
    request: SendActionAlertRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SendActionAlertResponse) => void,
  ): ClientUnaryCall;
  sendQuestProgress(
    request: SendQuestProgressRequest,
    callback: (error: ServiceError | null, response: SendQuestProgressResponse) => void,
  ): ClientUnaryCall;
  sendQuestProgress(
    request: SendQuestProgressRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SendQuestProgressResponse) => void,
  ): ClientUnaryCall;
  sendQuestProgress(
    request: SendQuestProgressRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SendQuestProgressResponse) => void,
  ): ClientUnaryCall;
  sendMilestoneAlert(
    request: SendMilestoneAlertRequest,
    callback: (error: ServiceError | null, response: SendMilestoneAlertResponse) => void,
  ): ClientUnaryCall;
  sendMilestoneAlert(
    request: SendMilestoneAlertRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SendMilestoneAlertResponse) => void,
  ): ClientUnaryCall;
  sendMilestoneAlert(
    request: SendMilestoneAlertRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SendMilestoneAlertResponse) => void,
  ): ClientUnaryCall;
  sendRiskEvent(
    request: SendRiskEventRequest,
    callback: (error: ServiceError | null, response: SendRiskEventResponse) => void,
  ): ClientUnaryCall;
  sendRiskEvent(
    request: SendRiskEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SendRiskEventResponse) => void,
  ): ClientUnaryCall;
  sendRiskEvent(
    request: SendRiskEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SendRiskEventResponse) => void,
  ): ClientUnaryCall;
}

export const TelegramServiceClient = makeGenericClientConstructor(
  TelegramServiceService,
  "telegram.TelegramService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): TelegramServiceClient;
  service: typeof TelegramServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
