# golangci-lint configuration for NeuraTrade
# This configuration establishes a quality baseline for the codebase.
#
# Baseline Rationale:
# - errcheck: Critical for catching unchecked errors that could cause silent failures
# - govet: Essential for catching common programming mistakes
# - ineffassign: Prevents unused variable assignments that indicate bugs
# - staticcheck: Comprehensive static analysis for code quality
# - unused: Removes dead code to reduce maintenance burden
# - copyloopvar: Prevents common loop variable copy bugs
#
# Additional Linters (not enabled by default due to migration phase):
# - misspell: Spelling errors in comments/docs (can be noisy)
# - gocyclo: Complexity checking (may need higher thresholds)
# - funlen: Function length limits (existing codebase has violations)
#
# See PR feedback in gh-87 for full discussion.

version: "2"

linters:
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - errname
    - asciicheck
    - bidichk

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
        - unusedwrite

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: false
