version: "2"

linters:
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - errname
    - asciicheck
    - bidichk

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
        - unusedwrite

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - copyloopvar
    - path: test/
      linters:
        - all
    - path: \.pb\.go
      linters:
        - all

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - .git
    - test
