version: "2"

linters:
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - errname
    - asciicheck
    - bidichk

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
        - unusedwrite

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
