export const VALIDATED_BTC_GRID_CANDIDATE = {
  exchange: "bitget-futures",
  symbol: "BTC/USDT:USDT",
  timeframe: "15m",
  productType: "USDT-FUTURES",
  gridStepPct: 1,
  gridMaxGrids: 1.5,
  gridPauseAfterLossBars: 12,
  feePct: 0.06,
  slippageBps: 2,
  trendFilterPeriod: 0,
  onlyWithTrend: false,
  targetRatio: 1,
  chopGateAdx: 30,
  leverage: 1,
  maxPositionSizePct: 50,
  maxDrawdownPct: 5,
  maxDailyLossPct: 2,
} as const;
