// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: telegram_service.proto

package telegram

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Existing messages
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ParseMode     string                 `protobuf:"bytes,3,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_telegram_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

type SendMessageResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Ok        bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Structured error code for programmatic handling
	// Values: USER_BLOCKED, CHAT_NOT_FOUND, RATE_LIMITED, INVALID_REQUEST, NETWORK_ERROR, TIMEOUT, INTERNAL_ERROR, UNKNOWN
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Seconds to wait before retrying (only set for RATE_LIMITED errors)
	RetryAfter    int32 `protobuf:"varint,5,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_telegram_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendMessageResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SendMessageResponse) GetRetryAfter() int32 {
	if x != nil {
		return x.RetryAfter
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_telegram_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_telegram_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Action Alert (Task 3.5.1) - for trade notifications
type SendActionAlertRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatId          string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Action          string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "BUY", "SELL", "LIQUIDATE"
	Asset           string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Price           string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Size            string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	Strategy        string                 `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Reasoning       string                 `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	RiskCheckPassed bool                   `protobuf:"varint,8,opt,name=risk_check_passed,json=riskCheckPassed,proto3" json:"risk_check_passed,omitempty"`
	QuestId         string                 `protobuf:"bytes,9,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendActionAlertRequest) Reset() {
	*x = SendActionAlertRequest{}
	mi := &file_telegram_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionAlertRequest) ProtoMessage() {}

func (x *SendActionAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionAlertRequest.ProtoReflect.Descriptor instead.
func (*SendActionAlertRequest) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendActionAlertRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendActionAlertRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SendActionAlertRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *SendActionAlertRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SendActionAlertRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *SendActionAlertRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SendActionAlertRequest) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *SendActionAlertRequest) GetRiskCheckPassed() bool {
	if x != nil {
		return x.RiskCheckPassed
	}
	return false
}

func (x *SendActionAlertRequest) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

type SendActionAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActionAlertResponse) Reset() {
	*x = SendActionAlertResponse{}
	mi := &file_telegram_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionAlertResponse) ProtoMessage() {}

func (x *SendActionAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionAlertResponse.ProtoReflect.Descriptor instead.
func (*SendActionAlertResponse) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{5}
}

func (x *SendActionAlertResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendActionAlertResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendActionAlertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Quest Progress (Task 3.5.2) - for quest updates
type SendQuestProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	QuestName     string                 `protobuf:"bytes,3,opt,name=quest_name,json=questName,proto3" json:"quest_name,omitempty"`
	Current       int32                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Target        int32                  `protobuf:"varint,5,opt,name=target,proto3" json:"target,omitempty"`
	Percent       int32                  `protobuf:"varint,6,opt,name=percent,proto3" json:"percent,omitempty"`
	TimeRemaining string                 `protobuf:"bytes,7,opt,name=time_remaining,json=timeRemaining,proto3" json:"time_remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendQuestProgressRequest) Reset() {
	*x = SendQuestProgressRequest{}
	mi := &file_telegram_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendQuestProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendQuestProgressRequest) ProtoMessage() {}

func (x *SendQuestProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendQuestProgressRequest.ProtoReflect.Descriptor instead.
func (*SendQuestProgressRequest) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{6}
}

func (x *SendQuestProgressRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendQuestProgressRequest) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *SendQuestProgressRequest) GetQuestName() string {
	if x != nil {
		return x.QuestName
	}
	return ""
}

func (x *SendQuestProgressRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *SendQuestProgressRequest) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *SendQuestProgressRequest) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *SendQuestProgressRequest) GetTimeRemaining() string {
	if x != nil {
		return x.TimeRemaining
	}
	return ""
}

type SendQuestProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendQuestProgressResponse) Reset() {
	*x = SendQuestProgressResponse{}
	mi := &file_telegram_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendQuestProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendQuestProgressResponse) ProtoMessage() {}

func (x *SendQuestProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendQuestProgressResponse.ProtoReflect.Descriptor instead.
func (*SendQuestProgressResponse) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{7}
}

func (x *SendQuestProgressResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendQuestProgressResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendQuestProgressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Milestone Alert (Task 3.5.3) - for fund milestones
type SendMilestoneAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	NextTarget    string                 `protobuf:"bytes,4,opt,name=next_target,json=nextTarget,proto3" json:"next_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMilestoneAlertRequest) Reset() {
	*x = SendMilestoneAlertRequest{}
	mi := &file_telegram_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMilestoneAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMilestoneAlertRequest) ProtoMessage() {}

func (x *SendMilestoneAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMilestoneAlertRequest.ProtoReflect.Descriptor instead.
func (*SendMilestoneAlertRequest) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendMilestoneAlertRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMilestoneAlertRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendMilestoneAlertRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SendMilestoneAlertRequest) GetNextTarget() string {
	if x != nil {
		return x.NextTarget
	}
	return ""
}

type SendMilestoneAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMilestoneAlertResponse) Reset() {
	*x = SendMilestoneAlertResponse{}
	mi := &file_telegram_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMilestoneAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMilestoneAlertResponse) ProtoMessage() {}

func (x *SendMilestoneAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMilestoneAlertResponse.ProtoReflect.Descriptor instead.
func (*SendMilestoneAlertResponse) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{9}
}

func (x *SendMilestoneAlertResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendMilestoneAlertResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMilestoneAlertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Risk Event (Task 3.5.4) - for risk notifications
type SendRiskEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "kill_switch", "liquidation", "margin_call"
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`                    // "warning", "critical"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRiskEventRequest) Reset() {
	*x = SendRiskEventRequest{}
	mi := &file_telegram_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRiskEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRiskEventRequest) ProtoMessage() {}

func (x *SendRiskEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRiskEventRequest.ProtoReflect.Descriptor instead.
func (*SendRiskEventRequest) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{10}
}

func (x *SendRiskEventRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendRiskEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SendRiskEventRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SendRiskEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendRiskEventRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type SendRiskEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRiskEventResponse) Reset() {
	*x = SendRiskEventResponse{}
	mi := &file_telegram_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRiskEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRiskEventResponse) ProtoMessage() {}

func (x *SendRiskEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRiskEventResponse.ProtoReflect.Descriptor instead.
func (*SendRiskEventResponse) Descriptor() ([]byte, []int) {
	return file_telegram_service_proto_rawDescGZIP(), []int{11}
}

func (x *SendRiskEventResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendRiskEventResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendRiskEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_telegram_service_proto protoreflect.FileDescriptor

const file_telegram_service_proto_rawDesc = "" +
	"\n" +
	"\x16telegram_service.proto\x12\btelegram\"`\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x03 \x01(\tR\tparseMode\"Z\n" +
	"\x13SendMessageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\"\x8a\x02\n" +
	"\x16SendActionAlertRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\x1a\n" +
	"\bstrategy\x18\x06 \x01(\tR\bstrategy\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12*\n" +
	"\x11risk_check_passed\x18\b \x01(\bR\x0friskCheckPassed\x12\x19\n" +
	"\bquest_id\x18\t \x01(\tR\aquestId\"^\n" +
	"\x17SendActionAlertResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xe0\x01\n" +
	"\x18SendQuestProgressRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\x12\x1d\n" +
	"\n" +
	"quest_name\x18\x03 \x01(\tR\tquestName\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x05R\acurrent\x12\x16\n" +
	"\x06target\x18\x05 \x01(\x05R\x06target\x12\x18\n" +
	"\apercent\x18\x06 \x01(\x05R\apercent\x12%\n" +
	"\x0etime_remaining\x18\a \x01(\tR\rtimeRemaining\"`\n" +
	"\x19SendQuestProgressResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x83\x01\n" +
	"\x19SendMilestoneAlertRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x1f\n" +
	"\vnext_target\x18\x04 \x01(\tR\n" +
	"nextTarget\"a\n" +
	"\x1aSendMilestoneAlertResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x87\x02\n" +
	"\x14SendRiskEventRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12E\n" +
	"\adetails\x18\x05 \x03(\v2+.telegram.SendRiskEventRequest.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x15SendRiskEventResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x92\x04\n" +
	"\x0fTelegramService\x12J\n" +
	"\vSendMessage\x12\x1c.telegram.SendMessageRequest\x1a\x1d.telegram.SendMessageResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.telegram.HealthCheckRequest\x1a\x1d.telegram.HealthCheckResponse\x12V\n" +
	"\x0fSendActionAlert\x12 .telegram.SendActionAlertRequest\x1a!.telegram.SendActionAlertResponse\x12\\\n" +
	"\x11SendQuestProgress\x12\".telegram.SendQuestProgressRequest\x1a#.telegram.SendQuestProgressResponse\x12_\n" +
	"\x12SendMilestoneAlert\x12#.telegram.SendMilestoneAlertRequest\x1a$.telegram.SendMilestoneAlertResponse\x12P\n" +
	"\rSendRiskEvent\x12\x1e.telegram.SendRiskEventRequest\x1a\x1f.telegram.SendRiskEventResponseBDZBgithub.com/irfandi/neuratrade/services/backend-api/pkg/pb/telegramb\x06proto3"

var (
	file_telegram_service_proto_rawDescOnce sync.Once
	file_telegram_service_proto_rawDescData []byte
)

func file_telegram_service_proto_rawDescGZIP() []byte {
	file_telegram_service_proto_rawDescOnce.Do(func() {
		file_telegram_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telegram_service_proto_rawDesc), len(file_telegram_service_proto_rawDesc)))
	})
	return file_telegram_service_proto_rawDescData
}

var file_telegram_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_telegram_service_proto_goTypes = []any{
	(*SendMessageRequest)(nil),         // 0: telegram.SendMessageRequest
	(*SendMessageResponse)(nil),        // 1: telegram.SendMessageResponse
	(*HealthCheckRequest)(nil),         // 2: telegram.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 3: telegram.HealthCheckResponse
	(*SendActionAlertRequest)(nil),     // 4: telegram.SendActionAlertRequest
	(*SendActionAlertResponse)(nil),    // 5: telegram.SendActionAlertResponse
	(*SendQuestProgressRequest)(nil),   // 6: telegram.SendQuestProgressRequest
	(*SendQuestProgressResponse)(nil),  // 7: telegram.SendQuestProgressResponse
	(*SendMilestoneAlertRequest)(nil),  // 8: telegram.SendMilestoneAlertRequest
	(*SendMilestoneAlertResponse)(nil), // 9: telegram.SendMilestoneAlertResponse
	(*SendRiskEventRequest)(nil),       // 10: telegram.SendRiskEventRequest
	(*SendRiskEventResponse)(nil),      // 11: telegram.SendRiskEventResponse
	nil,                                // 12: telegram.SendRiskEventRequest.DetailsEntry
}
var file_telegram_service_proto_depIdxs = []int32{
	12, // 0: telegram.SendRiskEventRequest.details:type_name -> telegram.SendRiskEventRequest.DetailsEntry
	0,  // 1: telegram.TelegramService.SendMessage:input_type -> telegram.SendMessageRequest
	2,  // 2: telegram.TelegramService.HealthCheck:input_type -> telegram.HealthCheckRequest
	4,  // 3: telegram.TelegramService.SendActionAlert:input_type -> telegram.SendActionAlertRequest
	6,  // 4: telegram.TelegramService.SendQuestProgress:input_type -> telegram.SendQuestProgressRequest
	8,  // 5: telegram.TelegramService.SendMilestoneAlert:input_type -> telegram.SendMilestoneAlertRequest
	10, // 6: telegram.TelegramService.SendRiskEvent:input_type -> telegram.SendRiskEventRequest
	1,  // 7: telegram.TelegramService.SendMessage:output_type -> telegram.SendMessageResponse
	3,  // 8: telegram.TelegramService.HealthCheck:output_type -> telegram.HealthCheckResponse
	5,  // 9: telegram.TelegramService.SendActionAlert:output_type -> telegram.SendActionAlertResponse
	7,  // 10: telegram.TelegramService.SendQuestProgress:output_type -> telegram.SendQuestProgressResponse
	9,  // 11: telegram.TelegramService.SendMilestoneAlert:output_type -> telegram.SendMilestoneAlertResponse
	11, // 12: telegram.TelegramService.SendRiskEvent:output_type -> telegram.SendRiskEventResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_telegram_service_proto_init() }
func file_telegram_service_proto_init() {
	if File_telegram_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telegram_service_proto_rawDesc), len(file_telegram_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telegram_service_proto_goTypes,
		DependencyIndexes: file_telegram_service_proto_depIdxs,
		MessageInfos:      file_telegram_service_proto_msgTypes,
	}.Build()
	File_telegram_service_proto = out.File
	file_telegram_service_proto_goTypes = nil
	file_telegram_service_proto_depIdxs = nil
}
