// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: telegram_service.proto

package telegram

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramService_SendMessage_FullMethodName        = "/telegram.TelegramService/SendMessage"
	TelegramService_HealthCheck_FullMethodName        = "/telegram.TelegramService/HealthCheck"
	TelegramService_SendActionAlert_FullMethodName    = "/telegram.TelegramService/SendActionAlert"
	TelegramService_SendQuestProgress_FullMethodName  = "/telegram.TelegramService/SendQuestProgress"
	TelegramService_SendMilestoneAlert_FullMethodName = "/telegram.TelegramService/SendMilestoneAlert"
	TelegramService_SendRiskEvent_FullMethodName      = "/telegram.TelegramService/SendRiskEvent"
)

// TelegramServiceClient is the client API for TelegramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramServiceClient interface {
	// Existing RPCs
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// BD EPIC 3: New RPCs for live streaming and notifications
	SendActionAlert(ctx context.Context, in *SendActionAlertRequest, opts ...grpc.CallOption) (*SendActionAlertResponse, error)
	SendQuestProgress(ctx context.Context, in *SendQuestProgressRequest, opts ...grpc.CallOption) (*SendQuestProgressResponse, error)
	SendMilestoneAlert(ctx context.Context, in *SendMilestoneAlertRequest, opts ...grpc.CallOption) (*SendMilestoneAlertResponse, error)
	SendRiskEvent(ctx context.Context, in *SendRiskEventRequest, opts ...grpc.CallOption) (*SendRiskEventResponse, error)
}

type telegramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramServiceClient(cc grpc.ClientConnInterface) TelegramServiceClient {
	return &telegramServiceClient{cc}
}

func (c *telegramServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TelegramService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendActionAlert(ctx context.Context, in *SendActionAlertRequest, opts ...grpc.CallOption) (*SendActionAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendActionAlertResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendActionAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendQuestProgress(ctx context.Context, in *SendQuestProgressRequest, opts ...grpc.CallOption) (*SendQuestProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendQuestProgressResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendQuestProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendMilestoneAlert(ctx context.Context, in *SendMilestoneAlertRequest, opts ...grpc.CallOption) (*SendMilestoneAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMilestoneAlertResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendMilestoneAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendRiskEvent(ctx context.Context, in *SendRiskEventRequest, opts ...grpc.CallOption) (*SendRiskEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRiskEventResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendRiskEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramServiceServer is the server API for TelegramService service.
// All implementations must embed UnimplementedTelegramServiceServer
// for forward compatibility.
type TelegramServiceServer interface {
	// Existing RPCs
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// BD EPIC 3: New RPCs for live streaming and notifications
	SendActionAlert(context.Context, *SendActionAlertRequest) (*SendActionAlertResponse, error)
	SendQuestProgress(context.Context, *SendQuestProgressRequest) (*SendQuestProgressResponse, error)
	SendMilestoneAlert(context.Context, *SendMilestoneAlertRequest) (*SendMilestoneAlertResponse, error)
	SendRiskEvent(context.Context, *SendRiskEventRequest) (*SendRiskEventResponse, error)
	mustEmbedUnimplementedTelegramServiceServer()
}

// UnimplementedTelegramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramServiceServer struct{}

func (UnimplementedTelegramServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedTelegramServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTelegramServiceServer) SendActionAlert(context.Context, *SendActionAlertRequest) (*SendActionAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendActionAlert not implemented")
}
func (UnimplementedTelegramServiceServer) SendQuestProgress(context.Context, *SendQuestProgressRequest) (*SendQuestProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendQuestProgress not implemented")
}
func (UnimplementedTelegramServiceServer) SendMilestoneAlert(context.Context, *SendMilestoneAlertRequest) (*SendMilestoneAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMilestoneAlert not implemented")
}
func (UnimplementedTelegramServiceServer) SendRiskEvent(context.Context, *SendRiskEventRequest) (*SendRiskEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRiskEvent not implemented")
}
func (UnimplementedTelegramServiceServer) mustEmbedUnimplementedTelegramServiceServer() {}
func (UnimplementedTelegramServiceServer) testEmbeddedByValue()                         {}

// UnsafeTelegramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramServiceServer will
// result in compilation errors.
type UnsafeTelegramServiceServer interface {
	mustEmbedUnimplementedTelegramServiceServer()
}

func RegisterTelegramServiceServer(s grpc.ServiceRegistrar, srv TelegramServiceServer) {
	// If the following call panics, it indicates UnimplementedTelegramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramService_ServiceDesc, srv)
}

func _TelegramService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendActionAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendActionAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendActionAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendActionAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendActionAlert(ctx, req.(*SendActionAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendQuestProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendQuestProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendQuestProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendQuestProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendQuestProgress(ctx, req.(*SendQuestProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendMilestoneAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMilestoneAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendMilestoneAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendMilestoneAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendMilestoneAlert(ctx, req.(*SendMilestoneAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendRiskEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRiskEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendRiskEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendRiskEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendRiskEvent(ctx, req.(*SendRiskEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramService_ServiceDesc is the grpc.ServiceDesc for TelegramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telegram.TelegramService",
	HandlerType: (*TelegramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _TelegramService_SendMessage_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TelegramService_HealthCheck_Handler,
		},
		{
			MethodName: "SendActionAlert",
			Handler:    _TelegramService_SendActionAlert_Handler,
		},
		{
			MethodName: "SendQuestProgress",
			Handler:    _TelegramService_SendQuestProgress_Handler,
		},
		{
			MethodName: "SendMilestoneAlert",
			Handler:    _TelegramService_SendMilestoneAlert_Handler,
		},
		{
			MethodName: "SendRiskEvent",
			Handler:    _TelegramService_SendRiskEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telegram_service.proto",
}
